/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_hijabella_collection;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class BarangKeluarFrom extends BaseForm {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BarangKeluarFrom.class.getName());

    /**
     * Creates new form BarangKeluarFrom
     */
    public BarangKeluarFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDashboard5 = new javax.swing.JButton();
        btnDataProduk5 = new javax.swing.JButton();
        btnDataSupplier5 = new javax.swing.JButton();
        btnBarangMasuk5 = new javax.swing.JButton();
        btnBarangKeluar5 = new javax.swing.JButton();
        btnlLaporan5 = new javax.swing.JButton();
        btnSetting5 = new javax.swing.JButton();
        btnAbout5 = new javax.swing.JButton();
        btnLogout5 = new javax.swing.JButton();
        btnAllNotificationx6 = new javax.swing.JButton();
        lblLiveTotalPenjualan = new javax.swing.JLabel();
        lblLiveTotalBarangKeluar = new javax.swing.JLabel();
        cbKodeBarang2 = new javax.swing.JComboBox<>();
        txtMasukkanNamaBarang2 = new javax.swing.JTextField();
        txtMasukkanJumlahKeluar2 = new javax.swing.JTextField();
        txtMasukkanTanggal2 = new javax.swing.JTextField();
        lblKalender2 = new javax.swing.JLabel();
        btnSimpanData2 = new javax.swing.JButton();
        btnReset2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBarangKeluar = new javax.swing.JTable();
        btnBacktPage2 = new javax.swing.JButton();
        lblNoHalamanActive2 = new javax.swing.JLabel();
        btnNextPage2 = new javax.swing.JButton();
        txtMasukkanKeterangan = new javax.swing.JTextField();
        lblBackgroundBarangKeluar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDashboard5.setForeground(new java.awt.Color(201, 160, 160));
        btnDashboard5.setText("Dashboard");
        btnDashboard5.setBorder(null);
        btnDashboard5.setBorderPainted(false);
        btnDashboard5.setContentAreaFilled(false);
        btnDashboard5.setFocusPainted(false);
        btnDashboard5.setFocusable(false);
        btnDashboard5.addActionListener(this::btnDashboard5ActionPerformed);
        getContentPane().add(btnDashboard5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, 30));

        btnDataProduk5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataProduk5.setForeground(new java.awt.Color(201, 160, 160));
        btnDataProduk5.setText("Data Produk");
        btnDataProduk5.setBorder(null);
        btnDataProduk5.setBorderPainted(false);
        btnDataProduk5.setContentAreaFilled(false);
        btnDataProduk5.setFocusPainted(false);
        btnDataProduk5.setFocusable(false);
        btnDataProduk5.addActionListener(this::btnDataProduk5ActionPerformed);
        getContentPane().add(btnDataProduk5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, 20));

        btnDataSupplier5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataSupplier5.setForeground(new java.awt.Color(201, 160, 160));
        btnDataSupplier5.setText("Data Supplier");
        btnDataSupplier5.setBorder(null);
        btnDataSupplier5.setBorderPainted(false);
        btnDataSupplier5.setContentAreaFilled(false);
        btnDataSupplier5.setFocusPainted(false);
        btnDataSupplier5.setFocusable(false);
        btnDataSupplier5.addActionListener(this::btnDataSupplier5ActionPerformed);
        getContentPane().add(btnDataSupplier5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, 20));

        btnBarangMasuk5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangMasuk5.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangMasuk5.setText("Barang Masuk");
        btnBarangMasuk5.setBorder(null);
        btnBarangMasuk5.setBorderPainted(false);
        btnBarangMasuk5.setContentAreaFilled(false);
        btnBarangMasuk5.setFocusPainted(false);
        btnBarangMasuk5.setFocusable(false);
        btnBarangMasuk5.addActionListener(this::btnBarangMasuk5ActionPerformed);
        getContentPane().add(btnBarangMasuk5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, 30));

        btnBarangKeluar5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangKeluar5.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangKeluar5.setText("Barang Keluar");
        btnBarangKeluar5.setBorder(null);
        btnBarangKeluar5.setBorderPainted(false);
        btnBarangKeluar5.setContentAreaFilled(false);
        btnBarangKeluar5.setFocusPainted(false);
        btnBarangKeluar5.setFocusable(false);
        btnBarangKeluar5.addActionListener(this::btnBarangKeluar5ActionPerformed);
        getContentPane().add(btnBarangKeluar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 110, 30));

        btnlLaporan5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnlLaporan5.setForeground(new java.awt.Color(201, 160, 160));
        btnlLaporan5.setText("Laporan");
        btnlLaporan5.setBorder(null);
        btnlLaporan5.setBorderPainted(false);
        btnlLaporan5.setContentAreaFilled(false);
        btnlLaporan5.setFocusPainted(false);
        btnlLaporan5.setFocusable(false);
        btnlLaporan5.addActionListener(this::btnlLaporan5ActionPerformed);
        getContentPane().add(btnlLaporan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, 30));

        btnSetting5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSetting5.setForeground(new java.awt.Color(201, 160, 160));
        btnSetting5.setText("Setting");
        btnSetting5.setBorder(null);
        btnSetting5.setBorderPainted(false);
        btnSetting5.setContentAreaFilled(false);
        btnSetting5.setFocusPainted(false);
        btnSetting5.setFocusable(false);
        btnSetting5.addActionListener(this::btnSetting5ActionPerformed);
        getContentPane().add(btnSetting5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 110, 30));

        btnAbout5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAbout5.setForeground(new java.awt.Color(201, 160, 160));
        btnAbout5.setText("About");
        btnAbout5.setBorder(null);
        btnAbout5.setBorderPainted(false);
        btnAbout5.setContentAreaFilled(false);
        btnAbout5.setFocusPainted(false);
        btnAbout5.setFocusable(false);
        btnAbout5.addActionListener(this::btnAbout5ActionPerformed);
        getContentPane().add(btnAbout5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 110, 40));

        btnLogout5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout5.setForeground(new java.awt.Color(201, 160, 160));
        btnLogout5.setText("Logout");
        btnLogout5.setBorder(null);
        btnLogout5.setBorderPainted(false);
        btnLogout5.setContentAreaFilled(false);
        btnLogout5.setFocusPainted(false);
        btnLogout5.setFocusable(false);
        btnLogout5.addActionListener(this::btnLogout5ActionPerformed);
        getContentPane().add(btnLogout5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 110, 40));

        btnAllNotificationx6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/notification.png"))); // NOI18N
        btnAllNotificationx6.setBorder(null);
        btnAllNotificationx6.setBorderPainted(false);
        btnAllNotificationx6.setContentAreaFilled(false);
        btnAllNotificationx6.setFocusPainted(false);
        btnAllNotificationx6.setFocusable(false);
        btnAllNotificationx6.setRequestFocusEnabled(false);
        getContentPane().add(btnAllNotificationx6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 60, 50));

        lblLiveTotalPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLiveTotalPenjualan.setText("95");
        getContentPane().add(lblLiveTotalPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 130, 20));

        lblLiveTotalBarangKeluar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLiveTotalBarangKeluar.setText("95");
        getContentPane().add(lblLiveTotalBarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 130, 20));

        cbKodeBarang2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FH001" }));
        cbKodeBarang2.setBorder(null);
        cbKodeBarang2.setFocusable(false);
        cbKodeBarang2.setRequestFocusEnabled(false);
        getContentPane().add(cbKodeBarang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 230, 10));

        txtMasukkanNamaBarang2.setBackground(new java.awt.Color(250, 245, 241));
        txtMasukkanNamaBarang2.setForeground(new java.awt.Color(153, 153, 153));
        txtMasukkanNamaBarang2.setText("Masukkan Nama Barang");
        txtMasukkanNamaBarang2.setBorder(null);
        txtMasukkanNamaBarang2.setFocusable(false);
        txtMasukkanNamaBarang2.setRequestFocusEnabled(false);
        getContentPane().add(txtMasukkanNamaBarang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 296, 230, 20));

        txtMasukkanJumlahKeluar2.setForeground(new java.awt.Color(153, 153, 153));
        txtMasukkanJumlahKeluar2.setText("Masukkan Jumlah Keluar");
        txtMasukkanJumlahKeluar2.setBorder(null);
        txtMasukkanJumlahKeluar2.setFocusable(false);
        txtMasukkanJumlahKeluar2.setRequestFocusEnabled(false);
        getContentPane().add(txtMasukkanJumlahKeluar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 230, -1));

        txtMasukkanTanggal2.setForeground(new java.awt.Color(153, 153, 153));
        txtMasukkanTanggal2.setText("17/06/2026");
        txtMasukkanTanggal2.setBorder(null);
        txtMasukkanTanggal2.setFocusable(false);
        txtMasukkanTanggal2.setRequestFocusEnabled(false);
        getContentPane().add(txtMasukkanTanggal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 100, 20));

        lblKalender2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/kalender 20px.png"))); // NOI18N
        getContentPane().add(lblKalender2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, -1, 20));

        btnSimpanData2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpanData2.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanData2.setText("Simpan");
        btnSimpanData2.setBorder(null);
        btnSimpanData2.setBorderPainted(false);
        btnSimpanData2.setContentAreaFilled(false);
        btnSimpanData2.setFocusPainted(false);
        btnSimpanData2.setFocusable(false);
        btnSimpanData2.setRequestFocusEnabled(false);
        getContentPane().add(btnSimpanData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 486, 60, 20));

        btnReset2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset2.setForeground(new java.awt.Color(102, 28, 28));
        btnReset2.setText("Reset");
        btnReset2.setBorder(null);
        btnReset2.setBorderPainted(false);
        btnReset2.setContentAreaFilled(false);
        btnReset2.setFocusPainted(false);
        btnReset2.setFocusable(false);
        btnReset2.setRequestFocusEnabled(false);
        getContentPane().add(btnReset2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 70, 30));

        jtBarangKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Kode Barang", "Nama Barang", "Jumlah", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtBarangKeluar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 197, 480, 250));

        btnBacktPage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/back 20px.png"))); // NOI18N
        btnBacktPage2.setBorder(null);
        btnBacktPage2.setBorderPainted(false);
        btnBacktPage2.setContentAreaFilled(false);
        btnBacktPage2.setFocusPainted(false);
        btnBacktPage2.setFocusable(false);
        btnBacktPage2.setRequestFocusEnabled(false);
        btnBacktPage2.addActionListener(this::btnBacktPage2ActionPerformed);
        getContentPane().add(btnBacktPage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 30, 40));

        lblNoHalamanActive2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNoHalamanActive2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoHalamanActive2.setText("1");
        getContentPane().add(lblNoHalamanActive2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 40, 40));

        btnNextPage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/next 20px.png"))); // NOI18N
        btnNextPage2.setBorder(null);
        btnNextPage2.setBorderPainted(false);
        btnNextPage2.setContentAreaFilled(false);
        btnNextPage2.setFocusPainted(false);
        btnNextPage2.setFocusable(false);
        btnNextPage2.setRequestFocusEnabled(false);
        btnNextPage2.addActionListener(this::btnNextPage2ActionPerformed);
        getContentPane().add(btnNextPage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 30, 40));

        txtMasukkanKeterangan.setForeground(new java.awt.Color(153, 153, 153));
        txtMasukkanKeterangan.setText("Masukkan Keterangan");
        txtMasukkanKeterangan.setBorder(null);
        txtMasukkanKeterangan.setFocusable(false);
        txtMasukkanKeterangan.setRequestFocusEnabled(false);
        getContentPane().add(txtMasukkanKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 454, 230, -1));

        lblBackgroundBarangKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/background/barangkeluar.png"))); // NOI18N
        getContentPane().add(lblBackgroundBarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetting5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetting5ActionPerformed
        // TODO add your handling code here:
        setting();
    }//GEN-LAST:event_btnSetting5ActionPerformed

    private void btnAbout5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbout5ActionPerformed
        // TODO add your handling code here:
        about();
    }//GEN-LAST:event_btnAbout5ActionPerformed

    private void btnBacktPage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktPage2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBacktPage2ActionPerformed

    private void btnNextPage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPage2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextPage2ActionPerformed

    private void btnDashboard5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard5ActionPerformed
        // TODO add your handling code here:
        dashboard();
    }//GEN-LAST:event_btnDashboard5ActionPerformed

    private void btnDataProduk5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataProduk5ActionPerformed
        // TODO add your handling code here:
        dataProduk();
    }//GEN-LAST:event_btnDataProduk5ActionPerformed

    private void btnDataSupplier5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSupplier5ActionPerformed
        // TODO add your handling code here:
        dataSupplier();
    }//GEN-LAST:event_btnDataSupplier5ActionPerformed

    private void btnBarangMasuk5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangMasuk5ActionPerformed
        // TODO add your handling code here:
        barangMasuk();
    }//GEN-LAST:event_btnBarangMasuk5ActionPerformed

    private void btnBarangKeluar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangKeluar5ActionPerformed
        // TODO add your handling code here:
        halamanAktif("Barang Keluar");
    }//GEN-LAST:event_btnBarangKeluar5ActionPerformed

    private void btnlLaporan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlLaporan5ActionPerformed
        // TODO add your handling code here:
        laporan();
    }//GEN-LAST:event_btnlLaporan5ActionPerformed

    private void btnLogout5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout5ActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_btnLogout5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BarangKeluarFrom().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout5;
    private javax.swing.JButton btnAllNotificationx6;
    private javax.swing.JButton btnBacktPage2;
    private javax.swing.JButton btnBarangKeluar5;
    private javax.swing.JButton btnBarangMasuk5;
    private javax.swing.JButton btnDashboard5;
    private javax.swing.JButton btnDataProduk5;
    private javax.swing.JButton btnDataSupplier5;
    private javax.swing.JButton btnLogout5;
    private javax.swing.JButton btnNextPage2;
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnSetting5;
    private javax.swing.JButton btnSimpanData2;
    private javax.swing.JButton btnlLaporan5;
    private javax.swing.JComboBox<String> cbKodeBarang2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtBarangKeluar;
    private javax.swing.JLabel lblBackgroundBarangKeluar;
    private javax.swing.JLabel lblKalender2;
    private javax.swing.JLabel lblLiveTotalBarangKeluar;
    private javax.swing.JLabel lblLiveTotalPenjualan;
    private javax.swing.JLabel lblNoHalamanActive2;
    private javax.swing.JTextField txtMasukkanJumlahKeluar2;
    private javax.swing.JTextField txtMasukkanKeterangan;
    private javax.swing.JTextField txtMasukkanNamaBarang2;
    private javax.swing.JTextField txtMasukkanTanggal2;
    // End of variables declaration//GEN-END:variables
}
