/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_hijabella_collection;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class BarangMasukFrom extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BarangMasukFrom.class.getName());

    /**
     * Creates new form BarangMasukFrom
     */
    public BarangMasukFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAllNotificationx5 = new javax.swing.JButton();
        btnDashboard4 = new javax.swing.JButton();
        btnDataProduk4 = new javax.swing.JButton();
        btnDataSupplier4 = new javax.swing.JButton();
        btnBarangMasuk4 = new javax.swing.JButton();
        btnBarangKeluar4 = new javax.swing.JButton();
        btnlLaporan4 = new javax.swing.JButton();
        btnSetting4 = new javax.swing.JButton();
        btnAbout4 = new javax.swing.JButton();
        btnLogout4 = new javax.swing.JButton();
        lblLiveTotalBarangMasuk = new javax.swing.JLabel();
        lblLiveTotalTransaksi = new javax.swing.JLabel();
        btnSimpanData = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblKalender = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBarangMasuk = new javax.swing.JTable();
        btnBacktPage2 = new javax.swing.JButton();
        btnNextPage2 = new javax.swing.JButton();
        lblNoHalamanActive2 = new javax.swing.JLabel();
        cbKodeBarang = new javax.swing.JComboBox<>();
        cbIDSupplier = new javax.swing.JComboBox<>();
        txtMasukkanNamaBarang = new javax.swing.JTextField();
        txtMasukkanJumlahMasuk = new javax.swing.JTextField();
        txtMasukkanTanggal = new javax.swing.JTextField();
        lblBackgroundBarangMasuk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAllNotificationx5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/notification.png"))); // NOI18N
        btnAllNotificationx5.setBorder(null);
        btnAllNotificationx5.setBorderPainted(false);
        btnAllNotificationx5.setContentAreaFilled(false);
        btnAllNotificationx5.setFocusPainted(false);
        btnAllNotificationx5.setFocusable(false);
        btnAllNotificationx5.setRequestFocusEnabled(false);
        getContentPane().add(btnAllNotificationx5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 60, 50));

        btnDashboard4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDashboard4.setForeground(new java.awt.Color(201, 160, 160));
        btnDashboard4.setText("Dashboard");
        btnDashboard4.setBorder(null);
        btnDashboard4.setBorderPainted(false);
        btnDashboard4.setContentAreaFilled(false);
        btnDashboard4.setFocusPainted(false);
        btnDashboard4.setFocusable(false);
        getContentPane().add(btnDashboard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, 30));

        btnDataProduk4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataProduk4.setForeground(new java.awt.Color(201, 160, 160));
        btnDataProduk4.setText("Data Produk");
        btnDataProduk4.setBorder(null);
        btnDataProduk4.setBorderPainted(false);
        btnDataProduk4.setContentAreaFilled(false);
        btnDataProduk4.setFocusPainted(false);
        btnDataProduk4.setFocusable(false);
        getContentPane().add(btnDataProduk4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, 20));

        btnDataSupplier4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataSupplier4.setForeground(new java.awt.Color(201, 160, 160));
        btnDataSupplier4.setText("Data Supplier");
        btnDataSupplier4.setBorder(null);
        btnDataSupplier4.setBorderPainted(false);
        btnDataSupplier4.setContentAreaFilled(false);
        btnDataSupplier4.setFocusPainted(false);
        btnDataSupplier4.setFocusable(false);
        getContentPane().add(btnDataSupplier4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, 20));

        btnBarangMasuk4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangMasuk4.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangMasuk4.setText("Barang Masuk");
        btnBarangMasuk4.setBorder(null);
        btnBarangMasuk4.setBorderPainted(false);
        btnBarangMasuk4.setContentAreaFilled(false);
        btnBarangMasuk4.setFocusPainted(false);
        btnBarangMasuk4.setFocusable(false);
        getContentPane().add(btnBarangMasuk4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, 30));

        btnBarangKeluar4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangKeluar4.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangKeluar4.setText("Barang Keluar");
        btnBarangKeluar4.setBorder(null);
        btnBarangKeluar4.setBorderPainted(false);
        btnBarangKeluar4.setContentAreaFilled(false);
        btnBarangKeluar4.setFocusPainted(false);
        btnBarangKeluar4.setFocusable(false);
        getContentPane().add(btnBarangKeluar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 110, 30));

        btnlLaporan4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnlLaporan4.setForeground(new java.awt.Color(201, 160, 160));
        btnlLaporan4.setText("Laporan");
        btnlLaporan4.setBorder(null);
        btnlLaporan4.setBorderPainted(false);
        btnlLaporan4.setContentAreaFilled(false);
        btnlLaporan4.setFocusPainted(false);
        btnlLaporan4.setFocusable(false);
        getContentPane().add(btnlLaporan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, 30));

        btnSetting4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSetting4.setForeground(new java.awt.Color(201, 160, 160));
        btnSetting4.setText("Setting");
        btnSetting4.setBorder(null);
        btnSetting4.setBorderPainted(false);
        btnSetting4.setContentAreaFilled(false);
        btnSetting4.setFocusPainted(false);
        btnSetting4.setFocusable(false);
        btnSetting4.addActionListener(this::btnSetting4ActionPerformed);
        getContentPane().add(btnSetting4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 110, 30));

        btnAbout4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAbout4.setForeground(new java.awt.Color(201, 160, 160));
        btnAbout4.setText("About");
        btnAbout4.setBorder(null);
        btnAbout4.setBorderPainted(false);
        btnAbout4.setContentAreaFilled(false);
        btnAbout4.setFocusPainted(false);
        btnAbout4.setFocusable(false);
        btnAbout4.addActionListener(this::btnAbout4ActionPerformed);
        getContentPane().add(btnAbout4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 110, 40));

        btnLogout4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout4.setForeground(new java.awt.Color(201, 160, 160));
        btnLogout4.setText("Logout");
        btnLogout4.setBorder(null);
        btnLogout4.setBorderPainted(false);
        btnLogout4.setContentAreaFilled(false);
        btnLogout4.setFocusPainted(false);
        btnLogout4.setFocusable(false);
        getContentPane().add(btnLogout4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 110, 40));

        lblLiveTotalBarangMasuk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLiveTotalBarangMasuk.setText("120");
        getContentPane().add(lblLiveTotalBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 130, 20));

        lblLiveTotalTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLiveTotalTransaksi.setText("8");
        getContentPane().add(lblLiveTotalTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 130, 20));

        btnSimpanData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpanData.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanData.setText("Simpan");
        btnSimpanData.setBorder(null);
        btnSimpanData.setBorderPainted(false);
        btnSimpanData.setContentAreaFilled(false);
        btnSimpanData.setFocusPainted(false);
        btnSimpanData.setFocusable(false);
        btnSimpanData.setRequestFocusEnabled(false);
        getContentPane().add(btnSimpanData, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 486, 60, 20));

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(102, 28, 28));
        btnReset.setText("Reset");
        btnReset.setBorder(null);
        btnReset.setBorderPainted(false);
        btnReset.setContentAreaFilled(false);
        btnReset.setFocusPainted(false);
        btnReset.setFocusable(false);
        btnReset.setRequestFocusEnabled(false);
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 70, 30));

        lblKalender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/kalender 20px.png"))); // NOI18N
        getContentPane().add(lblKalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, -1, 20));

        jtBarangMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "ID Supplier", "Kode Barang", "Nama Barang", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtBarangMasuk);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 197, 480, 250));

        btnBacktPage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/back 20px.png"))); // NOI18N
        btnBacktPage2.setBorder(null);
        btnBacktPage2.setBorderPainted(false);
        btnBacktPage2.setContentAreaFilled(false);
        btnBacktPage2.setFocusPainted(false);
        btnBacktPage2.setFocusable(false);
        btnBacktPage2.setRequestFocusEnabled(false);
        btnBacktPage2.addActionListener(this::btnBacktPage2ActionPerformed);
        getContentPane().add(btnBacktPage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 30, 40));

        btnNextPage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/next 20px.png"))); // NOI18N
        btnNextPage2.setBorder(null);
        btnNextPage2.setBorderPainted(false);
        btnNextPage2.setContentAreaFilled(false);
        btnNextPage2.setFocusPainted(false);
        btnNextPage2.setFocusable(false);
        btnNextPage2.setRequestFocusEnabled(false);
        btnNextPage2.addActionListener(this::btnNextPage2ActionPerformed);
        getContentPane().add(btnNextPage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 30, 40));

        lblNoHalamanActive2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNoHalamanActive2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoHalamanActive2.setText("1");
        getContentPane().add(lblNoHalamanActive2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 40, 40));

        cbKodeBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FH001" }));
        cbKodeBarang.setBorder(null);
        cbKodeBarang.setFocusable(false);
        cbKodeBarang.setRequestFocusEnabled(false);
        getContentPane().add(cbKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 220, 10));

        cbIDSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP001" }));
        cbIDSupplier.setBorder(null);
        cbIDSupplier.setFocusable(false);
        cbIDSupplier.setRequestFocusEnabled(false);
        getContentPane().add(cbIDSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 220, 10));

        txtMasukkanNamaBarang.setBackground(new java.awt.Color(250, 245, 241));
        txtMasukkanNamaBarang.setForeground(new java.awt.Color(153, 153, 153));
        txtMasukkanNamaBarang.setText("Masukkan Nama Barang");
        txtMasukkanNamaBarang.setBorder(null);
        txtMasukkanNamaBarang.setFocusable(false);
        txtMasukkanNamaBarang.setRequestFocusEnabled(false);
        getContentPane().add(txtMasukkanNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 296, 220, 20));

        txtMasukkanJumlahMasuk.setForeground(new java.awt.Color(153, 153, 153));
        txtMasukkanJumlahMasuk.setText("Masukkan Jumlah Masuk");
        txtMasukkanJumlahMasuk.setBorder(null);
        txtMasukkanJumlahMasuk.setFocusable(false);
        txtMasukkanJumlahMasuk.setRequestFocusEnabled(false);
        getContentPane().add(txtMasukkanJumlahMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 220, -1));

        txtMasukkanTanggal.setForeground(new java.awt.Color(153, 153, 153));
        txtMasukkanTanggal.setText("17/06/2026");
        txtMasukkanTanggal.setBorder(null);
        txtMasukkanTanggal.setFocusable(false);
        txtMasukkanTanggal.setRequestFocusEnabled(false);
        getContentPane().add(txtMasukkanTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 100, 20));

        lblBackgroundBarangMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/background/barangmasuk.png"))); // NOI18N
        getContentPane().add(lblBackgroundBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetting4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetting4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetting4ActionPerformed

    private void btnAbout4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbout4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbout4ActionPerformed

    private void btnBacktPage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktPage2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBacktPage2ActionPerformed

    private void btnNextPage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPage2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextPage2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BarangMasukFrom().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout4;
    private javax.swing.JButton btnAllNotificationx5;
    private javax.swing.JButton btnBacktPage2;
    private javax.swing.JButton btnBarangKeluar4;
    private javax.swing.JButton btnBarangMasuk4;
    private javax.swing.JButton btnDashboard4;
    private javax.swing.JButton btnDataProduk4;
    private javax.swing.JButton btnDataSupplier4;
    private javax.swing.JButton btnLogout4;
    private javax.swing.JButton btnNextPage2;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSetting4;
    private javax.swing.JButton btnSimpanData;
    private javax.swing.JButton btnlLaporan4;
    private javax.swing.JComboBox<String> cbIDSupplier;
    private javax.swing.JComboBox<String> cbKodeBarang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtBarangMasuk;
    private javax.swing.JLabel lblBackgroundBarangMasuk;
    private javax.swing.JLabel lblKalender;
    private javax.swing.JLabel lblLiveTotalBarangMasuk;
    private javax.swing.JLabel lblLiveTotalTransaksi;
    private javax.swing.JLabel lblNoHalamanActive2;
    private javax.swing.JTextField txtMasukkanJumlahMasuk;
    private javax.swing.JTextField txtMasukkanNamaBarang;
    private javax.swing.JTextField txtMasukkanTanggal;
    // End of variables declaration//GEN-END:variables
}
