/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_hijabella_collection;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class DashboardFrom extends BaseForm {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrom.class.getName());

    /**
     * Creates new form DashboardFrom
     */
    public DashboardFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAllNotification1a = new javax.swing.JButton();
        btnDashboard1 = new javax.swing.JButton();
        btnDataProduk1 = new javax.swing.JButton();
        btnDataSupplier1 = new javax.swing.JButton();
        btnBarangMasuk1 = new javax.swing.JButton();
        btnBarangKeluar1 = new javax.swing.JButton();
        btnlLaporan1 = new javax.swing.JButton();
        btnSetting1 = new javax.swing.JButton();
        btnAbout1 = new javax.swing.JButton();
        btnLogout1 = new javax.swing.JButton();
        lblBarangKeluar = new javax.swing.JLabel();
        lblTotalProduk = new javax.swing.JLabel();
        lblBarangMasuk = new javax.swing.JLabel();
        lblRefStokMenipis = new javax.swing.JLabel();
        lblTeksStokMenipis = new javax.swing.JLabel();
        lblStokMenipis = new javax.swing.JLabel();
        lblPHH = new javax.swing.JLabel();
        lblBKB = new javax.swing.JLabel();
        lblBMM = new javax.swing.JLabel();
        lblTimePHH = new javax.swing.JLabel();
        lblTimeBMB = new javax.swing.JLabel();
        lblTimePHH1 = new javax.swing.JLabel();
        btnAllNotification = new javax.swing.JLabel();
        btnAllNotificationx1 = new javax.swing.JButton();
        lblNoHalamanActive3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBackPage1b = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnNextPage1b = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblBackgroundDashboard = new javax.swing.JLabel();

        btnAllNotification1a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/notification.png"))); // NOI18N
        btnAllNotification1a.setBorder(null);
        btnAllNotification1a.setBorderPainted(false);
        btnAllNotification1a.setContentAreaFilled(false);
        btnAllNotification1a.setFocusPainted(false);
        btnAllNotification1a.setFocusable(false);
        btnAllNotification1a.setRequestFocusEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDashboard1.setForeground(new java.awt.Color(201, 160, 160));
        btnDashboard1.setText("Dashboard");
        btnDashboard1.setBorder(null);
        btnDashboard1.setBorderPainted(false);
        btnDashboard1.setContentAreaFilled(false);
        btnDashboard1.setFocusPainted(false);
        btnDashboard1.setFocusable(false);
        btnDashboard1.addActionListener(this::btnDashboard1ActionPerformed);
        getContentPane().add(btnDashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, 30));

        btnDataProduk1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataProduk1.setForeground(new java.awt.Color(201, 160, 160));
        btnDataProduk1.setText("Data Produk");
        btnDataProduk1.setBorder(null);
        btnDataProduk1.setBorderPainted(false);
        btnDataProduk1.setContentAreaFilled(false);
        btnDataProduk1.setFocusPainted(false);
        btnDataProduk1.setFocusable(false);
        btnDataProduk1.addActionListener(this::btnDataProduk1ActionPerformed);
        getContentPane().add(btnDataProduk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, 20));

        btnDataSupplier1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataSupplier1.setForeground(new java.awt.Color(201, 160, 160));
        btnDataSupplier1.setText("Data Supplier");
        btnDataSupplier1.setBorder(null);
        btnDataSupplier1.setBorderPainted(false);
        btnDataSupplier1.setContentAreaFilled(false);
        btnDataSupplier1.setFocusPainted(false);
        btnDataSupplier1.setFocusable(false);
        btnDataSupplier1.addActionListener(this::btnDataSupplier1ActionPerformed);
        getContentPane().add(btnDataSupplier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, 20));

        btnBarangMasuk1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangMasuk1.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangMasuk1.setText("Barang Masuk");
        btnBarangMasuk1.setBorder(null);
        btnBarangMasuk1.setBorderPainted(false);
        btnBarangMasuk1.setContentAreaFilled(false);
        btnBarangMasuk1.setFocusPainted(false);
        btnBarangMasuk1.setFocusable(false);
        btnBarangMasuk1.addActionListener(this::btnBarangMasuk1ActionPerformed);
        getContentPane().add(btnBarangMasuk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, 30));

        btnBarangKeluar1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangKeluar1.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangKeluar1.setText("Barang Keluar");
        btnBarangKeluar1.setBorder(null);
        btnBarangKeluar1.setBorderPainted(false);
        btnBarangKeluar1.setContentAreaFilled(false);
        btnBarangKeluar1.setFocusPainted(false);
        btnBarangKeluar1.setFocusable(false);
        btnBarangKeluar1.addActionListener(this::btnBarangKeluar1ActionPerformed);
        getContentPane().add(btnBarangKeluar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 110, 30));

        btnlLaporan1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnlLaporan1.setForeground(new java.awt.Color(201, 160, 160));
        btnlLaporan1.setText("Laporan");
        btnlLaporan1.setBorder(null);
        btnlLaporan1.setBorderPainted(false);
        btnlLaporan1.setContentAreaFilled(false);
        btnlLaporan1.setFocusPainted(false);
        btnlLaporan1.setFocusable(false);
        btnlLaporan1.addActionListener(this::btnlLaporan1ActionPerformed);
        getContentPane().add(btnlLaporan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, 30));

        btnSetting1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSetting1.setForeground(new java.awt.Color(201, 160, 160));
        btnSetting1.setText("Setting");
        btnSetting1.setBorder(null);
        btnSetting1.setBorderPainted(false);
        btnSetting1.setContentAreaFilled(false);
        btnSetting1.setFocusPainted(false);
        btnSetting1.setFocusable(false);
        btnSetting1.addActionListener(this::btnSetting1ActionPerformed);
        getContentPane().add(btnSetting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 110, 30));

        btnAbout1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAbout1.setForeground(new java.awt.Color(201, 160, 160));
        btnAbout1.setText("About");
        btnAbout1.setBorder(null);
        btnAbout1.setBorderPainted(false);
        btnAbout1.setContentAreaFilled(false);
        btnAbout1.setFocusPainted(false);
        btnAbout1.setFocusable(false);
        btnAbout1.addActionListener(this::btnAbout1ActionPerformed);
        getContentPane().add(btnAbout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 110, 40));

        btnLogout1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout1.setForeground(new java.awt.Color(201, 160, 160));
        btnLogout1.setText("Logout");
        btnLogout1.setBorder(null);
        btnLogout1.setBorderPainted(false);
        btnLogout1.setContentAreaFilled(false);
        btnLogout1.setFocusPainted(false);
        btnLogout1.setFocusable(false);
        btnLogout1.addActionListener(this::btnLogout1ActionPerformed);
        getContentPane().add(btnLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 110, 40));

        lblBarangKeluar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBarangKeluar.setText("95");
        getContentPane().add(lblBarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 80, 30));

        lblTotalProduk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalProduk.setText("350");
        getContentPane().add(lblTotalProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 80, 30));

        lblBarangMasuk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBarangMasuk.setText("120");
        getContentPane().add(lblBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 80, 30));

        lblRefStokMenipis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRefStokMenipis.setText("2");
        getContentPane().add(lblRefStokMenipis, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 80, 30));

        lblTeksStokMenipis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTeksStokMenipis.setText("Produk Hampir Habis");
        getContentPane().add(lblTeksStokMenipis, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 160, -1));

        lblStokMenipis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStokMenipis.setText("0");
        getContentPane().add(lblStokMenipis, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, -1, -1));

        lblPHH.setText("Gamis, Hijab Dewasa, Dll...");
        getContentPane().add(lblPHH, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 170, -1));

        lblBKB.setText("Alat Tulis (25 pcs)");
        getContentPane().add(lblBKB, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 140, -1));

        lblBMM.setText("Alat Tulis (25 pcs)");
        getContentPane().add(lblBMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 140, -1));

        lblTimePHH.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblTimePHH.setForeground(new java.awt.Color(153, 153, 153));
        lblTimePHH.setText("10 minutes ago");
        getContentPane().add(lblTimePHH, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, -1, 20));

        lblTimeBMB.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblTimeBMB.setForeground(new java.awt.Color(153, 153, 153));
        lblTimeBMB.setText("10 minutes ago");
        getContentPane().add(lblTimeBMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, -1, 20));

        lblTimePHH1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblTimePHH1.setForeground(new java.awt.Color(153, 153, 153));
        lblTimePHH1.setText("10 minutes ago");
        getContentPane().add(lblTimePHH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, -1, 20));

        btnAllNotification.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAllNotification.setForeground(new java.awt.Color(51, 153, 255));
        btnAllNotification.setText("Lihat Semua");
        getContentPane().add(btnAllNotification, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, -1, -1));

        btnAllNotificationx1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/notification.png"))); // NOI18N
        btnAllNotificationx1.setBorder(null);
        btnAllNotificationx1.setBorderPainted(false);
        btnAllNotificationx1.setContentAreaFilled(false);
        btnAllNotificationx1.setFocusPainted(false);
        btnAllNotificationx1.setFocusable(false);
        btnAllNotificationx1.setRequestFocusEnabled(false);
        getContentPane().add(btnAllNotificationx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 60, 60));

        lblNoHalamanActive3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNoHalamanActive3.setForeground(new java.awt.Color(255, 255, 255));
        lblNoHalamanActive3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoHalamanActive3.setText("1");
        getContentPane().add(lblNoHalamanActive3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 50, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnBackPage1b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/back 20px.png"))); // NOI18N
        btnBackPage1b.setBorder(null);
        btnBackPage1b.setBorderPainted(false);
        btnBackPage1b.setContentAreaFilled(false);
        btnBackPage1b.setFocusPainted(false);
        btnBackPage1b.setFocusable(false);
        btnBackPage1b.setRequestFocusEnabled(false);
        btnBackPage1b.addActionListener(this::btnBackPage1bActionPerformed);
        jPanel2.add(btnBackPage1b);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 40, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnNextPage1b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/next 20px.png"))); // NOI18N
        btnNextPage1b.setBorder(null);
        btnNextPage1b.setBorderPainted(false);
        btnNextPage1b.setContentAreaFilled(false);
        btnNextPage1b.setFocusPainted(false);
        btnNextPage1b.setFocusable(false);
        btnNextPage1b.setRequestFocusEnabled(false);
        btnNextPage1b.addActionListener(this::btnNextPage1bActionPerformed);
        jPanel1.add(btnNextPage1b);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 40, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Product", "Nama Product", "Stok", "Harga", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 247, 450, 240));

        lblBackgroundDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/background/dashboard.png"))); // NOI18N
        getContentPane().add(lblBackgroundDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetting1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetting1ActionPerformed
        // TODO add your handling code here:
        setting();
    }//GEN-LAST:event_btnSetting1ActionPerformed

    private void btnAbout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbout1ActionPerformed
        // TODO add your handling code here:
        about();
    }//GEN-LAST:event_btnAbout1ActionPerformed

    private void btnNextPage1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPage1bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextPage1bActionPerformed

    private void btnBackPage1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackPage1bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackPage1bActionPerformed

    private void btnDashboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard1ActionPerformed
        // TODO add your handling code here:
        halamanAktif("Dashboard");
    }//GEN-LAST:event_btnDashboard1ActionPerformed

    private void btnDataProduk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataProduk1ActionPerformed
        // TODO add your handling code here:
        dataProduk();
    }//GEN-LAST:event_btnDataProduk1ActionPerformed

    private void btnDataSupplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSupplier1ActionPerformed
        // TODO add your handling code here:
        dataSupplier();
    }//GEN-LAST:event_btnDataSupplier1ActionPerformed

    private void btnBarangMasuk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangMasuk1ActionPerformed
        // TODO add your handling code here:
        barangMasuk();
    }//GEN-LAST:event_btnBarangMasuk1ActionPerformed

    private void btnBarangKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangKeluar1ActionPerformed
        // TODO add your handling code here:
        barangKeluar();
    }//GEN-LAST:event_btnBarangKeluar1ActionPerformed

    private void btnlLaporan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlLaporan1ActionPerformed
        // TODO add your handling code here:
        laporan();
    }//GEN-LAST:event_btnlLaporan1ActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_btnLogout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrom().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout1;
    private javax.swing.JLabel btnAllNotification;
    private javax.swing.JButton btnAllNotification1a;
    private javax.swing.JButton btnAllNotificationx1;
    private javax.swing.JButton btnBackPage1b;
    private javax.swing.JButton btnBarangKeluar1;
    private javax.swing.JButton btnBarangMasuk1;
    private javax.swing.JButton btnDashboard1;
    private javax.swing.JButton btnDataProduk1;
    private javax.swing.JButton btnDataSupplier1;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnNextPage1b;
    private javax.swing.JButton btnSetting1;
    private javax.swing.JButton btnlLaporan1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBKB;
    private javax.swing.JLabel lblBMM;
    private javax.swing.JLabel lblBackgroundDashboard;
    private javax.swing.JLabel lblBarangKeluar;
    private javax.swing.JLabel lblBarangMasuk;
    private javax.swing.JLabel lblNoHalamanActive3;
    private javax.swing.JLabel lblPHH;
    private javax.swing.JLabel lblRefStokMenipis;
    private javax.swing.JLabel lblStokMenipis;
    private javax.swing.JLabel lblTeksStokMenipis;
    private javax.swing.JLabel lblTimeBMB;
    private javax.swing.JLabel lblTimePHH;
    private javax.swing.JLabel lblTimePHH1;
    private javax.swing.JLabel lblTotalProduk;
    // End of variables declaration//GEN-END:variables
}
