/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_hijabella_collection;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class DataProdukFrom extends BaseForm {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DataProdukFrom.class.getName());

    /**
     * Creates new form DataProdukForm
     */
    public DataProdukFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDashboard2 = new javax.swing.JButton();
        btnDataProduk2 = new javax.swing.JButton();
        btnDataSupplier2 = new javax.swing.JButton();
        btnBarangMasuk2 = new javax.swing.JButton();
        btnBarangKeluar2 = new javax.swing.JButton();
        btnlLaporan2 = new javax.swing.JButton();
        btnSetting2 = new javax.swing.JButton();
        btnAbout2 = new javax.swing.JButton();
        btnLogout2 = new javax.swing.JButton();
        cbAllKategori = new javax.swing.JComboBox<>();
        btnAllNotificationx2 = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        tctCariProduct = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDataProduk = new javax.swing.JTable();
        lblNoHalamanActive1 = new javax.swing.JLabel();
        btnNextPage = new javax.swing.JButton();
        btnNextPage1 = new javax.swing.JButton();
        lblBackgroundDataProduk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDashboard2.setForeground(new java.awt.Color(201, 160, 160));
        btnDashboard2.setText("Dashboard");
        btnDashboard2.setBorder(null);
        btnDashboard2.setBorderPainted(false);
        btnDashboard2.setContentAreaFilled(false);
        btnDashboard2.setFocusPainted(false);
        btnDashboard2.setFocusable(false);
        btnDashboard2.addActionListener(this::btnDashboard2ActionPerformed);
        getContentPane().add(btnDashboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, 30));

        btnDataProduk2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataProduk2.setForeground(new java.awt.Color(201, 160, 160));
        btnDataProduk2.setText("Data Produk");
        btnDataProduk2.setBorder(null);
        btnDataProduk2.setBorderPainted(false);
        btnDataProduk2.setContentAreaFilled(false);
        btnDataProduk2.setFocusPainted(false);
        btnDataProduk2.setFocusable(false);
        btnDataProduk2.addActionListener(this::btnDataProduk2ActionPerformed);
        getContentPane().add(btnDataProduk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, 20));

        btnDataSupplier2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataSupplier2.setForeground(new java.awt.Color(201, 160, 160));
        btnDataSupplier2.setText("Data Supplier");
        btnDataSupplier2.setBorder(null);
        btnDataSupplier2.setBorderPainted(false);
        btnDataSupplier2.setContentAreaFilled(false);
        btnDataSupplier2.setFocusPainted(false);
        btnDataSupplier2.setFocusable(false);
        btnDataSupplier2.addActionListener(this::btnDataSupplier2ActionPerformed);
        getContentPane().add(btnDataSupplier2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, 20));

        btnBarangMasuk2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangMasuk2.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangMasuk2.setText("Barang Masuk");
        btnBarangMasuk2.setBorder(null);
        btnBarangMasuk2.setBorderPainted(false);
        btnBarangMasuk2.setContentAreaFilled(false);
        btnBarangMasuk2.setFocusPainted(false);
        btnBarangMasuk2.setFocusable(false);
        btnBarangMasuk2.addActionListener(this::btnBarangMasuk2ActionPerformed);
        getContentPane().add(btnBarangMasuk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, 30));

        btnBarangKeluar2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangKeluar2.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangKeluar2.setText("Barang Keluar");
        btnBarangKeluar2.setBorder(null);
        btnBarangKeluar2.setBorderPainted(false);
        btnBarangKeluar2.setContentAreaFilled(false);
        btnBarangKeluar2.setFocusPainted(false);
        btnBarangKeluar2.setFocusable(false);
        btnBarangKeluar2.addActionListener(this::btnBarangKeluar2ActionPerformed);
        getContentPane().add(btnBarangKeluar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 110, 30));

        btnlLaporan2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnlLaporan2.setForeground(new java.awt.Color(201, 160, 160));
        btnlLaporan2.setText("Laporan");
        btnlLaporan2.setBorder(null);
        btnlLaporan2.setBorderPainted(false);
        btnlLaporan2.setContentAreaFilled(false);
        btnlLaporan2.setFocusPainted(false);
        btnlLaporan2.setFocusable(false);
        btnlLaporan2.addActionListener(this::btnlLaporan2ActionPerformed);
        getContentPane().add(btnlLaporan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, 30));

        btnSetting2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSetting2.setForeground(new java.awt.Color(201, 160, 160));
        btnSetting2.setText("Setting");
        btnSetting2.setBorder(null);
        btnSetting2.setBorderPainted(false);
        btnSetting2.setContentAreaFilled(false);
        btnSetting2.setFocusPainted(false);
        btnSetting2.setFocusable(false);
        btnSetting2.addActionListener(this::btnSetting2ActionPerformed);
        getContentPane().add(btnSetting2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 110, 30));

        btnAbout2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAbout2.setForeground(new java.awt.Color(201, 160, 160));
        btnAbout2.setText("About");
        btnAbout2.setBorder(null);
        btnAbout2.setBorderPainted(false);
        btnAbout2.setContentAreaFilled(false);
        btnAbout2.setFocusPainted(false);
        btnAbout2.setFocusable(false);
        btnAbout2.addActionListener(this::btnAbout2ActionPerformed);
        getContentPane().add(btnAbout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 110, 40));

        btnLogout2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout2.setForeground(new java.awt.Color(201, 160, 160));
        btnLogout2.setText("Logout");
        btnLogout2.setBorder(null);
        btnLogout2.setBorderPainted(false);
        btnLogout2.setContentAreaFilled(false);
        btnLogout2.setFocusPainted(false);
        btnLogout2.setFocusable(false);
        btnLogout2.addActionListener(this::btnLogout2ActionPerformed);
        getContentPane().add(btnLogout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 110, 40));

        cbAllKategori.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbAllKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Kategori", "Gamis", "Hijab Dewasa", "Hijab Anak", "Alat Tulis", "Mainan Anak" }));
        cbAllKategori.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbAllKategori.setFocusable(false);
        cbAllKategori.addActionListener(this::cbAllKategoriActionPerformed);
        getContentPane().add(cbAllKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 144, 150, 30));

        btnAllNotificationx2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/notification.png"))); // NOI18N
        btnAllNotificationx2.setBorder(null);
        btnAllNotificationx2.setBorderPainted(false);
        btnAllNotificationx2.setContentAreaFilled(false);
        btnAllNotificationx2.setFocusPainted(false);
        btnAllNotificationx2.setFocusable(false);
        btnAllNotificationx2.setRequestFocusEnabled(false);
        getContentPane().add(btnAllNotificationx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 60, 60));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/edit 20px.png"))); // NOI18N
        btnEdit.setBorder(null);
        btnEdit.setBorderPainted(false);
        btnEdit.setContentAreaFilled(false);
        btnEdit.setFocusPainted(false);
        btnEdit.setFocusable(false);
        btnEdit.setRequestFocusEnabled(false);
        btnEdit.addActionListener(this::btnEditActionPerformed);
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 50, 40));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/sampah 20 px.png"))); // NOI18N
        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.setFocusPainted(false);
        btnDelete.setFocusable(false);
        btnDelete.setRequestFocusEnabled(false);
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 50, 40));

        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.setBorder(null);
        btnTambah.setBorderPainted(false);
        btnTambah.setContentAreaFilled(false);
        btnTambah.setFocusPainted(false);
        btnTambah.setFocusable(false);
        btnTambah.setRequestFocusEnabled(false);
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 85, 110, 30));

        tctCariProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tctCariProduct.setForeground(new java.awt.Color(153, 153, 153));
        tctCariProduct.setText("Cari Product...");
        tctCariProduct.setBorder(null);
        tctCariProduct.setFocusable(false);
        tctCariProduct.setRequestFocusEnabled(false);
        getContentPane().add(tctCariProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 110, 20));

        jtDataProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Product", "Nama Barang", "Stok", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtDataProduk);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 740, 250));

        lblNoHalamanActive1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNoHalamanActive1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoHalamanActive1.setText("1");
        getContentPane().add(lblNoHalamanActive1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 40, 50));

        btnNextPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/next 20px.png"))); // NOI18N
        btnNextPage.setBorder(null);
        btnNextPage.setBorderPainted(false);
        btnNextPage.setContentAreaFilled(false);
        btnNextPage.setFocusPainted(false);
        btnNextPage.setFocusable(false);
        btnNextPage.setRequestFocusEnabled(false);
        btnNextPage.addActionListener(this::btnNextPageActionPerformed);
        getContentPane().add(btnNextPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, 30, 50));

        btnNextPage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/back 20px.png"))); // NOI18N
        btnNextPage1.setBorder(null);
        btnNextPage1.setBorderPainted(false);
        btnNextPage1.setContentAreaFilled(false);
        btnNextPage1.setFocusPainted(false);
        btnNextPage1.setFocusable(false);
        btnNextPage1.setRequestFocusEnabled(false);
        btnNextPage1.addActionListener(this::btnNextPage1ActionPerformed);
        getContentPane().add(btnNextPage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 30, 50));

        lblBackgroundDataProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/background/dataproduk.png"))); // NOI18N
        getContentPane().add(lblBackgroundDataProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataProduk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataProduk2ActionPerformed
        // TODO add your handling code here:
        halamanAktif("Data Produk");
    }//GEN-LAST:event_btnDataProduk2ActionPerformed

    private void btnSetting2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetting2ActionPerformed
        // TODO add your handling code here:
        setting();
    }//GEN-LAST:event_btnSetting2ActionPerformed

    private void btnAbout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbout2ActionPerformed
        // TODO add your handling code here:
        about();
    }//GEN-LAST:event_btnAbout2ActionPerformed

    private void cbAllKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAllKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAllKategoriActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextPageActionPerformed

    private void btnNextPage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPage1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextPage1ActionPerformed

    private void btnDashboard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard2ActionPerformed
        // TODO add your handling code here:
        dashboard();
    }//GEN-LAST:event_btnDashboard2ActionPerformed

    private void btnDataSupplier2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSupplier2ActionPerformed
        // TODO add your handling code here:
        dataSupplier();
    }//GEN-LAST:event_btnDataSupplier2ActionPerformed

    private void btnBarangMasuk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangMasuk2ActionPerformed
        // TODO add your handling code here:
        barangMasuk();
    }//GEN-LAST:event_btnBarangMasuk2ActionPerformed

    private void btnBarangKeluar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangKeluar2ActionPerformed
        // TODO add your handling code here:
        barangKeluar();
    }//GEN-LAST:event_btnBarangKeluar2ActionPerformed

    private void btnlLaporan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlLaporan2ActionPerformed
        // TODO add your handling code here:
        laporan();
    }//GEN-LAST:event_btnlLaporan2ActionPerformed

    private void btnLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout2ActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_btnLogout2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DataProdukFrom().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout2;
    private javax.swing.JButton btnAllNotificationx2;
    private javax.swing.JButton btnBarangKeluar2;
    private javax.swing.JButton btnBarangMasuk2;
    private javax.swing.JButton btnDashboard2;
    private javax.swing.JButton btnDataProduk2;
    private javax.swing.JButton btnDataSupplier2;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout2;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnNextPage1;
    private javax.swing.JButton btnSetting2;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnlLaporan2;
    private javax.swing.JComboBox<String> cbAllKategori;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtDataProduk;
    private javax.swing.JLabel lblBackgroundDataProduk;
    private javax.swing.JLabel lblNoHalamanActive1;
    private javax.swing.JTextField tctCariProduct;
    // End of variables declaration//GEN-END:variables
}
