/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_hijabella_collection;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class DataSupplierFrom extends BaseForm {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DataSupplierFrom.class.getName());

    /**
     * Creates new form DataSupplierForm
     */
    public DataSupplierFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDashboard3 = new javax.swing.JButton();
        btnDataProduk3 = new javax.swing.JButton();
        btnDataSupplier3 = new javax.swing.JButton();
        btnBarangMasuk3 = new javax.swing.JButton();
        btnBarangKeluar3 = new javax.swing.JButton();
        btnlLaporan3 = new javax.swing.JButton();
        btnSetting3 = new javax.swing.JButton();
        btnAbout3 = new javax.swing.JButton();
        btnLogout3 = new javax.swing.JButton();
        btnAllNotificationx3 = new javax.swing.JButton();
        tctCari = new javax.swing.JTextField();
        lblTotalSupplier = new javax.swing.JLabel();
        lblSupplierAktif = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblNoHalamanActive2 = new javax.swing.JLabel();
        btnBackPage1 = new javax.swing.JButton();
        btnNextPage1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDataSupplier = new javax.swing.JTable();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        lblBackgroundDataSupplier = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Supplier");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDashboard3.setForeground(new java.awt.Color(201, 160, 160));
        btnDashboard3.setText("Dashboard");
        btnDashboard3.setBorder(null);
        btnDashboard3.setBorderPainted(false);
        btnDashboard3.setContentAreaFilled(false);
        btnDashboard3.setFocusPainted(false);
        btnDashboard3.setFocusable(false);
        btnDashboard3.addActionListener(this::btnDashboard3ActionPerformed);
        getContentPane().add(btnDashboard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, 30));

        btnDataProduk3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataProduk3.setForeground(new java.awt.Color(201, 160, 160));
        btnDataProduk3.setText("Data Produk");
        btnDataProduk3.setBorder(null);
        btnDataProduk3.setBorderPainted(false);
        btnDataProduk3.setContentAreaFilled(false);
        btnDataProduk3.setFocusPainted(false);
        btnDataProduk3.setFocusable(false);
        btnDataProduk3.addActionListener(this::btnDataProduk3ActionPerformed);
        getContentPane().add(btnDataProduk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, 20));

        btnDataSupplier3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataSupplier3.setForeground(new java.awt.Color(201, 160, 160));
        btnDataSupplier3.setText("Data Supplier");
        btnDataSupplier3.setBorder(null);
        btnDataSupplier3.setBorderPainted(false);
        btnDataSupplier3.setContentAreaFilled(false);
        btnDataSupplier3.setFocusPainted(false);
        btnDataSupplier3.setFocusable(false);
        btnDataSupplier3.addActionListener(this::btnDataSupplier3ActionPerformed);
        getContentPane().add(btnDataSupplier3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, 20));

        btnBarangMasuk3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangMasuk3.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangMasuk3.setText("Barang Masuk");
        btnBarangMasuk3.setBorder(null);
        btnBarangMasuk3.setBorderPainted(false);
        btnBarangMasuk3.setContentAreaFilled(false);
        btnBarangMasuk3.setFocusPainted(false);
        btnBarangMasuk3.setFocusable(false);
        btnBarangMasuk3.addActionListener(this::btnBarangMasuk3ActionPerformed);
        getContentPane().add(btnBarangMasuk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, 30));

        btnBarangKeluar3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangKeluar3.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangKeluar3.setText("Barang Keluar");
        btnBarangKeluar3.setBorder(null);
        btnBarangKeluar3.setBorderPainted(false);
        btnBarangKeluar3.setContentAreaFilled(false);
        btnBarangKeluar3.setFocusPainted(false);
        btnBarangKeluar3.setFocusable(false);
        btnBarangKeluar3.addActionListener(this::btnBarangKeluar3ActionPerformed);
        getContentPane().add(btnBarangKeluar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 110, 30));

        btnlLaporan3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnlLaporan3.setForeground(new java.awt.Color(201, 160, 160));
        btnlLaporan3.setText("Laporan");
        btnlLaporan3.setBorder(null);
        btnlLaporan3.setBorderPainted(false);
        btnlLaporan3.setContentAreaFilled(false);
        btnlLaporan3.setFocusPainted(false);
        btnlLaporan3.setFocusable(false);
        btnlLaporan3.addActionListener(this::btnlLaporan3ActionPerformed);
        getContentPane().add(btnlLaporan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, 30));

        btnSetting3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSetting3.setForeground(new java.awt.Color(201, 160, 160));
        btnSetting3.setText("Setting");
        btnSetting3.setBorder(null);
        btnSetting3.setBorderPainted(false);
        btnSetting3.setContentAreaFilled(false);
        btnSetting3.setFocusPainted(false);
        btnSetting3.setFocusable(false);
        btnSetting3.addActionListener(this::btnSetting3ActionPerformed);
        getContentPane().add(btnSetting3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 110, 30));

        btnAbout3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAbout3.setForeground(new java.awt.Color(201, 160, 160));
        btnAbout3.setText("About");
        btnAbout3.setBorder(null);
        btnAbout3.setBorderPainted(false);
        btnAbout3.setContentAreaFilled(false);
        btnAbout3.setFocusPainted(false);
        btnAbout3.setFocusable(false);
        btnAbout3.addActionListener(this::btnAbout3ActionPerformed);
        getContentPane().add(btnAbout3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 110, 40));

        btnLogout3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout3.setForeground(new java.awt.Color(201, 160, 160));
        btnLogout3.setText("Logout");
        btnLogout3.setBorder(null);
        btnLogout3.setBorderPainted(false);
        btnLogout3.setContentAreaFilled(false);
        btnLogout3.setFocusPainted(false);
        btnLogout3.setFocusable(false);
        btnLogout3.addActionListener(this::btnLogout3ActionPerformed);
        getContentPane().add(btnLogout3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 110, 40));

        btnAllNotificationx3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/notification.png"))); // NOI18N
        btnAllNotificationx3.setBorder(null);
        btnAllNotificationx3.setBorderPainted(false);
        btnAllNotificationx3.setContentAreaFilled(false);
        btnAllNotificationx3.setFocusPainted(false);
        btnAllNotificationx3.setFocusable(false);
        btnAllNotificationx3.setRequestFocusEnabled(false);
        getContentPane().add(btnAllNotificationx3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 60, 60));

        tctCari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tctCari.setForeground(new java.awt.Color(153, 153, 153));
        tctCari.setText("Cari...");
        tctCari.setBorder(null);
        tctCari.setFocusable(false);
        tctCari.setRequestFocusEnabled(false);
        getContentPane().add(tctCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 110, 20));

        lblTotalSupplier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalSupplier.setText("8");
        getContentPane().add(lblTotalSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 130, 30));

        lblSupplierAktif.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSupplierAktif.setText("7");
        getContentPane().add(lblSupplierAktif, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 130, 30));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Tambah");
        btnAdd.setBorder(null);
        btnAdd.setBorderPainted(false);
        btnAdd.setContentAreaFilled(false);
        btnAdd.setFocusPainted(false);
        btnAdd.setFocusable(false);
        btnAdd.setRequestFocusEnabled(false);
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 110, 40));

        lblNoHalamanActive2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNoHalamanActive2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoHalamanActive2.setText("1");
        getContentPane().add(lblNoHalamanActive2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 40, 40));

        btnBackPage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/back 20px.png"))); // NOI18N
        btnBackPage1.setBorder(null);
        btnBackPage1.setBorderPainted(false);
        btnBackPage1.setContentAreaFilled(false);
        btnBackPage1.setFocusPainted(false);
        btnBackPage1.setFocusable(false);
        btnBackPage1.setRequestFocusEnabled(false);
        btnBackPage1.addActionListener(this::btnBackPage1ActionPerformed);
        getContentPane().add(btnBackPage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 30, 40));

        btnNextPage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/next 20px.png"))); // NOI18N
        btnNextPage1.setBorder(null);
        btnNextPage1.setBorderPainted(false);
        btnNextPage1.setContentAreaFilled(false);
        btnNextPage1.setFocusPainted(false);
        btnNextPage1.setFocusable(false);
        btnNextPage1.setRequestFocusEnabled(false);
        btnNextPage1.addActionListener(this::btnNextPage1ActionPerformed);
        getContentPane().add(btnNextPage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 490, 30, 40));

        jtDataSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Supplier", "Nama Supplier", "Alamat", "No WhatshApp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtDataSupplier);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 230, 750, 260));

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/edit 20px.png"))); // NOI18N
        btnUbah.setBorder(null);
        btnUbah.setBorderPainted(false);
        btnUbah.setContentAreaFilled(false);
        btnUbah.setFocusPainted(false);
        btnUbah.setFocusable(false);
        btnUbah.setRequestFocusEnabled(false);
        btnUbah.addActionListener(this::btnUbahActionPerformed);
        getContentPane().add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 50, 40));

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/sampah 20 px.png"))); // NOI18N
        btnHapus.setBorder(null);
        btnHapus.setBorderPainted(false);
        btnHapus.setContentAreaFilled(false);
        btnHapus.setFocusPainted(false);
        btnHapus.setFocusable(false);
        btnHapus.setRequestFocusEnabled(false);
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 50, 40));

        lblBackgroundDataSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/background/datasupplier.png"))); // NOI18N
        getContentPane().add(lblBackgroundDataSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetting3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetting3ActionPerformed
        // TODO add your handling code here:
        setting();
    }//GEN-LAST:event_btnSetting3ActionPerformed

    private void btnAbout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbout3ActionPerformed
        // TODO add your handling code here:
        about();
    }//GEN-LAST:event_btnAbout3ActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnNextPage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPage1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextPage1ActionPerformed

    private void btnBackPage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackPage1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackPage1ActionPerformed

    private void btnDashboard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard3ActionPerformed
        // TODO add your handling code here:
        dashboard();
    }//GEN-LAST:event_btnDashboard3ActionPerformed

    private void btnDataProduk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataProduk3ActionPerformed
        // TODO add your handling code here:
        dataProduk();
    }//GEN-LAST:event_btnDataProduk3ActionPerformed

    private void btnDataSupplier3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSupplier3ActionPerformed
        // TODO add your handling code here:
        halamanAktif("Data Supplier");
    }//GEN-LAST:event_btnDataSupplier3ActionPerformed

    private void btnBarangMasuk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangMasuk3ActionPerformed
        // TODO add your handling code here:
        barangMasuk();
    }//GEN-LAST:event_btnBarangMasuk3ActionPerformed

    private void btnBarangKeluar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangKeluar3ActionPerformed
        // TODO add your handling code here:
        barangKeluar();
    }//GEN-LAST:event_btnBarangKeluar3ActionPerformed

    private void btnlLaporan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlLaporan3ActionPerformed
        // TODO add your handling code here:
        laporan();
    }//GEN-LAST:event_btnlLaporan3ActionPerformed

    private void btnLogout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout3ActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_btnLogout3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DataSupplierFrom().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout3;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAllNotificationx3;
    private javax.swing.JButton btnBackPage1;
    private javax.swing.JButton btnBarangKeluar3;
    private javax.swing.JButton btnBarangMasuk3;
    private javax.swing.JButton btnDashboard3;
    private javax.swing.JButton btnDataProduk3;
    private javax.swing.JButton btnDataSupplier3;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout3;
    private javax.swing.JButton btnNextPage1;
    private javax.swing.JButton btnSetting3;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnlLaporan3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtDataSupplier;
    private javax.swing.JLabel lblBackgroundDataSupplier;
    private javax.swing.JLabel lblNoHalamanActive2;
    private javax.swing.JLabel lblSupplierAktif;
    private javax.swing.JLabel lblTotalSupplier;
    private javax.swing.JTextField tctCari;
    // End of variables declaration//GEN-END:variables
}
