/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_hijabella_collection;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class LaporanFrom extends BaseForm {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LaporanFrom.class.getName());

    /**
     * Creates new form LaporanFrom
     */
    public LaporanFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDashboard6 = new javax.swing.JButton();
        btnDataProduk6 = new javax.swing.JButton();
        btnDataSupplier6 = new javax.swing.JButton();
        btnBarangMasuk6 = new javax.swing.JButton();
        btnBarangKeluar6 = new javax.swing.JButton();
        btnlLaporan6 = new javax.swing.JButton();
        btnSetting6 = new javax.swing.JButton();
        btnAbout6 = new javax.swing.JButton();
        btnLogout6 = new javax.swing.JButton();
        lblLiveTotalSIF = new javax.swing.JLabel();
        lblLiveTotalBM = new javax.swing.JLabel();
        lblLiveTotalPenjualan = new javax.swing.JLabel();
        lblLiveTotalPHH = new javax.swing.JLabel();
        txtTanggalAkhir = new javax.swing.JTextField();
        lblKalender3a = new javax.swing.JLabel();
        txtTanggalAwal = new javax.swing.JTextField();
        lblKalender3b = new javax.swing.JLabel();
        cbJenisLaporan = new javax.swing.JComboBox<>();
        btnAllNotificationx7 = new javax.swing.JButton();
        btnNextPage1a = new javax.swing.JButton();
        lblNoHalamanActive1a = new javax.swing.JLabel();
        btnNextPage1b = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAllLaporan = new javax.swing.JTable();
        lblBackgroundLaporan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDashboard6.setForeground(new java.awt.Color(201, 160, 160));
        btnDashboard6.setText("Dashboard");
        btnDashboard6.setBorder(null);
        btnDashboard6.setBorderPainted(false);
        btnDashboard6.setContentAreaFilled(false);
        btnDashboard6.setFocusPainted(false);
        btnDashboard6.setFocusable(false);
        btnDashboard6.addActionListener(this::btnDashboard6ActionPerformed);
        getContentPane().add(btnDashboard6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, 30));

        btnDataProduk6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataProduk6.setForeground(new java.awt.Color(201, 160, 160));
        btnDataProduk6.setText("Data Produk");
        btnDataProduk6.setBorder(null);
        btnDataProduk6.setBorderPainted(false);
        btnDataProduk6.setContentAreaFilled(false);
        btnDataProduk6.setFocusPainted(false);
        btnDataProduk6.setFocusable(false);
        btnDataProduk6.addActionListener(this::btnDataProduk6ActionPerformed);
        getContentPane().add(btnDataProduk6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, 20));

        btnDataSupplier6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataSupplier6.setForeground(new java.awt.Color(201, 160, 160));
        btnDataSupplier6.setText("Data Supplier");
        btnDataSupplier6.setBorder(null);
        btnDataSupplier6.setBorderPainted(false);
        btnDataSupplier6.setContentAreaFilled(false);
        btnDataSupplier6.setFocusPainted(false);
        btnDataSupplier6.setFocusable(false);
        btnDataSupplier6.addActionListener(this::btnDataSupplier6ActionPerformed);
        getContentPane().add(btnDataSupplier6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, 20));

        btnBarangMasuk6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangMasuk6.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangMasuk6.setText("Barang Masuk");
        btnBarangMasuk6.setBorder(null);
        btnBarangMasuk6.setBorderPainted(false);
        btnBarangMasuk6.setContentAreaFilled(false);
        btnBarangMasuk6.setFocusPainted(false);
        btnBarangMasuk6.setFocusable(false);
        btnBarangMasuk6.addActionListener(this::btnBarangMasuk6ActionPerformed);
        getContentPane().add(btnBarangMasuk6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, 30));

        btnBarangKeluar6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangKeluar6.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangKeluar6.setText("Barang Keluar");
        btnBarangKeluar6.setBorder(null);
        btnBarangKeluar6.setBorderPainted(false);
        btnBarangKeluar6.setContentAreaFilled(false);
        btnBarangKeluar6.setFocusPainted(false);
        btnBarangKeluar6.setFocusable(false);
        btnBarangKeluar6.addActionListener(this::btnBarangKeluar6ActionPerformed);
        getContentPane().add(btnBarangKeluar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 110, 30));

        btnlLaporan6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnlLaporan6.setForeground(new java.awt.Color(201, 160, 160));
        btnlLaporan6.setText("Laporan");
        btnlLaporan6.setBorder(null);
        btnlLaporan6.setBorderPainted(false);
        btnlLaporan6.setContentAreaFilled(false);
        btnlLaporan6.setFocusPainted(false);
        btnlLaporan6.setFocusable(false);
        btnlLaporan6.addActionListener(this::btnlLaporan6ActionPerformed);
        getContentPane().add(btnlLaporan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, 30));

        btnSetting6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSetting6.setForeground(new java.awt.Color(201, 160, 160));
        btnSetting6.setText("Setting");
        btnSetting6.setBorder(null);
        btnSetting6.setBorderPainted(false);
        btnSetting6.setContentAreaFilled(false);
        btnSetting6.setFocusPainted(false);
        btnSetting6.setFocusable(false);
        btnSetting6.addActionListener(this::btnSetting6ActionPerformed);
        getContentPane().add(btnSetting6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 110, 30));

        btnAbout6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAbout6.setForeground(new java.awt.Color(201, 160, 160));
        btnAbout6.setText("About");
        btnAbout6.setBorder(null);
        btnAbout6.setBorderPainted(false);
        btnAbout6.setContentAreaFilled(false);
        btnAbout6.setFocusPainted(false);
        btnAbout6.setFocusable(false);
        btnAbout6.addActionListener(this::btnAbout6ActionPerformed);
        getContentPane().add(btnAbout6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 110, 40));

        btnLogout6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout6.setForeground(new java.awt.Color(201, 160, 160));
        btnLogout6.setText("Logout");
        btnLogout6.setBorder(null);
        btnLogout6.setBorderPainted(false);
        btnLogout6.setContentAreaFilled(false);
        btnLogout6.setFocusPainted(false);
        btnLogout6.setFocusable(false);
        btnLogout6.addActionListener(this::btnLogout6ActionPerformed);
        getContentPane().add(btnLogout6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 110, 40));

        lblLiveTotalSIF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLiveTotalSIF.setForeground(new java.awt.Color(255, 255, 255));
        lblLiveTotalSIF.setText("350");
        getContentPane().add(lblLiveTotalSIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 120, 20));

        lblLiveTotalBM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLiveTotalBM.setForeground(new java.awt.Color(96, 60, 17));
        lblLiveTotalBM.setText("120");
        getContentPane().add(lblLiveTotalBM, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 120, 20));

        lblLiveTotalPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLiveTotalPenjualan.setForeground(new java.awt.Color(124, 101, 82));
        lblLiveTotalPenjualan.setText("95");
        getContentPane().add(lblLiveTotalPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 120, 20));

        lblLiveTotalPHH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLiveTotalPHH.setForeground(new java.awt.Color(96, 60, 17));
        lblLiveTotalPHH.setText("2");
        getContentPane().add(lblLiveTotalPHH, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 120, 20));

        txtTanggalAkhir.setForeground(new java.awt.Color(153, 153, 153));
        txtTanggalAkhir.setText("17/06/2026");
        txtTanggalAkhir.setBorder(null);
        txtTanggalAkhir.setFocusable(false);
        txtTanggalAkhir.setRequestFocusEnabled(false);
        getContentPane().add(txtTanggalAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 90, -1));

        lblKalender3a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/kalender 20px.png"))); // NOI18N
        getContentPane().add(lblKalender3a, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, 20));

        txtTanggalAwal.setForeground(new java.awt.Color(153, 153, 153));
        txtTanggalAwal.setText("17/06/2026");
        txtTanggalAwal.setBorder(null);
        txtTanggalAwal.setFocusable(false);
        txtTanggalAwal.setRequestFocusEnabled(false);
        getContentPane().add(txtTanggalAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 90, -1));

        lblKalender3b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/kalender 20px.png"))); // NOI18N
        getContentPane().add(lblKalender3b, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, 20));

        cbJenisLaporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lihat Semua", "Data Barang", "Data Stok" }));
        cbJenisLaporan.setBorder(null);
        cbJenisLaporan.setFocusable(false);
        cbJenisLaporan.setRequestFocusEnabled(false);
        getContentPane().add(cbJenisLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 110, 20));

        btnAllNotificationx7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/notification.png"))); // NOI18N
        btnAllNotificationx7.setBorder(null);
        btnAllNotificationx7.setBorderPainted(false);
        btnAllNotificationx7.setContentAreaFilled(false);
        btnAllNotificationx7.setFocusPainted(false);
        btnAllNotificationx7.setFocusable(false);
        btnAllNotificationx7.setRequestFocusEnabled(false);
        getContentPane().add(btnAllNotificationx7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 60, 50));

        btnNextPage1a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/back 20px.png"))); // NOI18N
        btnNextPage1a.setBorder(null);
        btnNextPage1a.setBorderPainted(false);
        btnNextPage1a.setContentAreaFilled(false);
        btnNextPage1a.setFocusPainted(false);
        btnNextPage1a.setFocusable(false);
        btnNextPage1a.setRequestFocusEnabled(false);
        btnNextPage1a.addActionListener(this::btnNextPage1aActionPerformed);
        getContentPane().add(btnNextPage1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 30, 50));

        lblNoHalamanActive1a.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNoHalamanActive1a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoHalamanActive1a.setText("1");
        getContentPane().add(lblNoHalamanActive1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 40, 50));

        btnNextPage1b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/next 20px.png"))); // NOI18N
        btnNextPage1b.setBorder(null);
        btnNextPage1b.setBorderPainted(false);
        btnNextPage1b.setContentAreaFilled(false);
        btnNextPage1b.setFocusPainted(false);
        btnNextPage1b.setFocusable(false);
        btnNextPage1b.setRequestFocusEnabled(false);
        btnNextPage1b.addActionListener(this::btnNextPage1bActionPerformed);
        getContentPane().add(btnNextPage1b, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, 30, 50));

        jtAllLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Barang", "Stok Awal", "Barang Masuk", "Barang Keluar", "Stok Akhir", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtAllLaporan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 250, 750, 210));

        lblBackgroundLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/background/laporan.png"))); // NOI18N
        getContentPane().add(lblBackgroundLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetting6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetting6ActionPerformed
        // TODO add your handling code here:
        setting();
    }//GEN-LAST:event_btnSetting6ActionPerformed

    private void btnAbout6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbout6ActionPerformed
        // TODO add your handling code here:
        about();
    }//GEN-LAST:event_btnAbout6ActionPerformed

    private void btnNextPage1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPage1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextPage1aActionPerformed

    private void btnNextPage1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPage1bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextPage1bActionPerformed

    private void btnLogout6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout6ActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_btnLogout6ActionPerformed

    private void btnlLaporan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlLaporan6ActionPerformed
        // TODO add your handling code here:
        halamanAktif("Laporan");
    }//GEN-LAST:event_btnlLaporan6ActionPerformed

    private void btnBarangKeluar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangKeluar6ActionPerformed
        // TODO add your handling code here:
        barangKeluar();
    }//GEN-LAST:event_btnBarangKeluar6ActionPerformed

    private void btnBarangMasuk6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangMasuk6ActionPerformed
        // TODO add your handling code here:
        barangMasuk();
    }//GEN-LAST:event_btnBarangMasuk6ActionPerformed

    private void btnDataSupplier6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSupplier6ActionPerformed
        // TODO add your handling code here:
        dataSupplier();
    }//GEN-LAST:event_btnDataSupplier6ActionPerformed

    private void btnDataProduk6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataProduk6ActionPerformed
        // TODO add your handling code here:
        dataProduk();
    }//GEN-LAST:event_btnDataProduk6ActionPerformed

    private void btnDashboard6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard6ActionPerformed
        // TODO add your handling code here:
        dashboard();
    }//GEN-LAST:event_btnDashboard6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LaporanFrom().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout6;
    private javax.swing.JButton btnAllNotificationx7;
    private javax.swing.JButton btnBarangKeluar6;
    private javax.swing.JButton btnBarangMasuk6;
    private javax.swing.JButton btnDashboard6;
    private javax.swing.JButton btnDataProduk6;
    private javax.swing.JButton btnDataSupplier6;
    private javax.swing.JButton btnLogout6;
    private javax.swing.JButton btnNextPage1a;
    private javax.swing.JButton btnNextPage1b;
    private javax.swing.JButton btnSetting6;
    private javax.swing.JButton btnlLaporan6;
    private javax.swing.JComboBox<String> cbJenisLaporan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtAllLaporan;
    private javax.swing.JLabel lblBackgroundLaporan;
    private javax.swing.JLabel lblKalender3a;
    private javax.swing.JLabel lblKalender3b;
    private javax.swing.JLabel lblLiveTotalBM;
    private javax.swing.JLabel lblLiveTotalPHH;
    private javax.swing.JLabel lblLiveTotalPenjualan;
    private javax.swing.JLabel lblLiveTotalSIF;
    private javax.swing.JLabel lblNoHalamanActive1a;
    private javax.swing.JTextField txtTanggalAkhir;
    private javax.swing.JTextField txtTanggalAwal;
    // End of variables declaration//GEN-END:variables
}
