/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_hijabella_collection;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class LogoutForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogoutForm.class.getName());

    /**
     * Creates new form LogoutForm
     */
    public LogoutForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBatal = new javax.swing.JButton();
        btnBatal1 = new javax.swing.JButton();
        btnLogout9 = new javax.swing.JButton();
        btnDashboard9 = new javax.swing.JButton();
        btnDataProduk9 = new javax.swing.JButton();
        btnDataSupplier9 = new javax.swing.JButton();
        btnBarangMasuk9 = new javax.swing.JButton();
        btnBarangKeluar9 = new javax.swing.JButton();
        btnlLaporan9 = new javax.swing.JButton();
        btnSetting9 = new javax.swing.JButton();
        btnAbout9 = new javax.swing.JButton();
        lblBackgroundLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Keluar");
        btnBatal.setBorder(null);
        btnBatal.setBorderPainted(false);
        btnBatal.setContentAreaFilled(false);
        btnBatal.setFocusPainted(false);
        btnBatal.setFocusable(false);
        btnBatal.setRequestFocusEnabled(false);
        btnBatal.addActionListener(this::btnBatalActionPerformed);
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 110, 30));

        btnBatal1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBatal1.setForeground(new java.awt.Color(96, 60, 17));
        btnBatal1.setText("Batal");
        btnBatal1.setBorder(null);
        btnBatal1.setBorderPainted(false);
        btnBatal1.setContentAreaFilled(false);
        btnBatal1.setFocusPainted(false);
        btnBatal1.setFocusable(false);
        btnBatal1.addActionListener(this::btnBatal1ActionPerformed);
        getContentPane().add(btnBatal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 120, 30));

        btnLogout9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout9.setForeground(new java.awt.Color(201, 160, 160));
        btnLogout9.setText("Logout");
        btnLogout9.setBorder(null);
        btnLogout9.setBorderPainted(false);
        btnLogout9.setContentAreaFilled(false);
        btnLogout9.setFocusPainted(false);
        btnLogout9.setFocusable(false);
        getContentPane().add(btnLogout9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 110, 40));

        btnDashboard9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDashboard9.setForeground(new java.awt.Color(201, 160, 160));
        btnDashboard9.setText("Dashboard");
        btnDashboard9.setBorder(null);
        btnDashboard9.setBorderPainted(false);
        btnDashboard9.setContentAreaFilled(false);
        btnDashboard9.setFocusPainted(false);
        btnDashboard9.setFocusable(false);
        getContentPane().add(btnDashboard9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, 30));

        btnDataProduk9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataProduk9.setForeground(new java.awt.Color(201, 160, 160));
        btnDataProduk9.setText("Data Produk");
        btnDataProduk9.setBorder(null);
        btnDataProduk9.setBorderPainted(false);
        btnDataProduk9.setContentAreaFilled(false);
        btnDataProduk9.setFocusPainted(false);
        btnDataProduk9.setFocusable(false);
        getContentPane().add(btnDataProduk9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, 20));

        btnDataSupplier9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataSupplier9.setForeground(new java.awt.Color(201, 160, 160));
        btnDataSupplier9.setText("Data Supplier");
        btnDataSupplier9.setBorder(null);
        btnDataSupplier9.setBorderPainted(false);
        btnDataSupplier9.setContentAreaFilled(false);
        btnDataSupplier9.setFocusPainted(false);
        btnDataSupplier9.setFocusable(false);
        getContentPane().add(btnDataSupplier9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, 20));

        btnBarangMasuk9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangMasuk9.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangMasuk9.setText("Barang Masuk");
        btnBarangMasuk9.setBorder(null);
        btnBarangMasuk9.setBorderPainted(false);
        btnBarangMasuk9.setContentAreaFilled(false);
        btnBarangMasuk9.setFocusPainted(false);
        btnBarangMasuk9.setFocusable(false);
        getContentPane().add(btnBarangMasuk9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, 30));

        btnBarangKeluar9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangKeluar9.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangKeluar9.setText("Barang Keluar");
        btnBarangKeluar9.setBorder(null);
        btnBarangKeluar9.setBorderPainted(false);
        btnBarangKeluar9.setContentAreaFilled(false);
        btnBarangKeluar9.setFocusPainted(false);
        btnBarangKeluar9.setFocusable(false);
        getContentPane().add(btnBarangKeluar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 110, 30));

        btnlLaporan9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnlLaporan9.setForeground(new java.awt.Color(201, 160, 160));
        btnlLaporan9.setText("Laporan");
        btnlLaporan9.setBorder(null);
        btnlLaporan9.setBorderPainted(false);
        btnlLaporan9.setContentAreaFilled(false);
        btnlLaporan9.setFocusPainted(false);
        btnlLaporan9.setFocusable(false);
        getContentPane().add(btnlLaporan9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, 30));

        btnSetting9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSetting9.setForeground(new java.awt.Color(201, 160, 160));
        btnSetting9.setText("Setting");
        btnSetting9.setBorder(null);
        btnSetting9.setBorderPainted(false);
        btnSetting9.setContentAreaFilled(false);
        btnSetting9.setFocusPainted(false);
        btnSetting9.setFocusable(false);
        getContentPane().add(btnSetting9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 110, 30));

        btnAbout9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAbout9.setForeground(new java.awt.Color(201, 160, 160));
        btnAbout9.setText("About");
        btnAbout9.setBorder(null);
        btnAbout9.setBorderPainted(false);
        btnAbout9.setContentAreaFilled(false);
        btnAbout9.setFocusPainted(false);
        btnAbout9.setFocusable(false);
        btnAbout9.addActionListener(this::btnAbout9ActionPerformed);
        getContentPane().add(btnAbout9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 110, 40));

        lblBackgroundLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/background/logout.png"))); // NOI18N
        getContentPane().add(lblBackgroundLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatal1ActionPerformed

    private void btnAbout9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbout9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbout9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogoutForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout9;
    private javax.swing.JButton btnBarangKeluar9;
    private javax.swing.JButton btnBarangMasuk9;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatal1;
    private javax.swing.JButton btnDashboard9;
    private javax.swing.JButton btnDataProduk9;
    private javax.swing.JButton btnDataSupplier9;
    private javax.swing.JButton btnLogout9;
    private javax.swing.JButton btnSetting9;
    private javax.swing.JButton btnlLaporan9;
    private javax.swing.JLabel lblBackgroundLogout;
    // End of variables declaration//GEN-END:variables
}
