/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_hijabella_collection;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class MaintenanceForm extends javax.swing.JFrame {
    
    private String kembaliKe;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MaintenanceForm.class.getName());

    /**
     * Creates new form Maintenance
     */
    public MaintenanceForm() {
        initComponents();
    }
    
    void maintenance(String fitur, String kembaliKe) {
        this.kembaliKe = kembaliKe;
        jMaintenanceFitur.setText(fitur);
        jMaintenanceFitur.setText(
        "<html><center>" + "Fitur <b>" + fitur + "</b> sedang dalam<br>" + "Tahap Pengembangan." + "</center></html>"
        );
        
        btnKembali.setText("Kembali ke " + kembaliKe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMaintenanceFitur = new javax.swing.JLabel();
        jDeskripsi = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        lbBackgroundMaintenance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maintenance");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMaintenanceFitur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMaintenanceFitur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMaintenanceFitur.setText("<html><center>Fitur <b>Default</b> sedang dalam<br>Tahap pengembangan.</center></html>");
        getContentPane().add(jMaintenanceFitur, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 310, 50));

        jDeskripsi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDeskripsi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDeskripsi.setText("<html><center>Kami sedang mempersiapkan <br>Pengalaman terbaik untuk<br>Anda.</center></html>");
        getContentPane().add(jDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 210, 60));

        btnKembali.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(201, 160, 160));
        btnKembali.setText("Kembali ke");
        btnKembali.setBorder(null);
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.setFocusPainted(false);
        btnKembali.addActionListener(this::btnKembaliActionPerformed);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 340, 30));

        lbBackgroundMaintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/background/maintenance.png"))); // NOI18N
        getContentPane().add(lbBackgroundMaintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        btnKembali.setEnabled(false);

    new Thread(() -> {

        try {

            btnKembali.setText("Loading.");
            Thread.sleep(200);

            btnKembali.setText("Loading..");
            Thread.sleep(200);

            btnKembali.setText("Loading...");
            Thread.sleep(200);
            
            btnKembali.setText("Loading....");
            Thread.sleep(200);
            
            btnKembali.setText("Loading.....");
            Thread.sleep(200);

            javax.swing.SwingUtilities.invokeLater(() -> {

                if (kembaliKe.equals("Login")) {

    LoadingForm loading = new LoadingForm("Kembali", "Login");
    loading.setVisible(true);
    loading.mulaiLoading();

}

                dispose();

            });

        } catch (InterruptedException e) {

            e.printStackTrace();

            javax.swing.SwingUtilities.invokeLater(() -> {

                btnKembali.setText("Kembali ke " + kembaliKe);
                btnKembali.setEnabled(true);

            });

        }

    }).start();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MaintenanceForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jDeskripsi;
    private javax.swing.JLabel jMaintenanceFitur;
    private javax.swing.JLabel lbBackgroundMaintenance;
    // End of variables declaration//GEN-END:variables
}
