/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_hijabella_collection;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class SettingFrom extends BaseForm {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SettingFrom.class.getName());

    /**
     * Creates new form SettingFrom
     */
    public SettingFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDashboard7 = new javax.swing.JButton();
        btnDataProduk7 = new javax.swing.JButton();
        btnDataSupplier7 = new javax.swing.JButton();
        btnBarangMasuk7 = new javax.swing.JButton();
        btnBarangKeluar7 = new javax.swing.JButton();
        btnlLaporan7 = new javax.swing.JButton();
        btnSetting7 = new javax.swing.JButton();
        btnAbout7 = new javax.swing.JButton();
        btnLogout7 = new javax.swing.JButton();
        lblIdUser = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNamaLengkap = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblWhatshApp = new javax.swing.JLabel();
        btnRefPassword = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        btnRefWhatshApp = new javax.swing.JButton();
        btnRefEmail = new javax.swing.JButton();
        lblBackgroundSetting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Setting");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDashboard7.setForeground(new java.awt.Color(201, 160, 160));
        btnDashboard7.setText("Dashboard");
        btnDashboard7.setBorder(null);
        btnDashboard7.setBorderPainted(false);
        btnDashboard7.setContentAreaFilled(false);
        btnDashboard7.setFocusPainted(false);
        btnDashboard7.setFocusable(false);
        btnDashboard7.addActionListener(this::btnDashboard7ActionPerformed);
        getContentPane().add(btnDashboard7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, 30));

        btnDataProduk7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataProduk7.setForeground(new java.awt.Color(201, 160, 160));
        btnDataProduk7.setText("Data Produk");
        btnDataProduk7.setBorder(null);
        btnDataProduk7.setBorderPainted(false);
        btnDataProduk7.setContentAreaFilled(false);
        btnDataProduk7.setFocusPainted(false);
        btnDataProduk7.setFocusable(false);
        btnDataProduk7.addActionListener(this::btnDataProduk7ActionPerformed);
        getContentPane().add(btnDataProduk7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, 20));

        btnDataSupplier7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDataSupplier7.setForeground(new java.awt.Color(201, 160, 160));
        btnDataSupplier7.setText("Data Supplier");
        btnDataSupplier7.setBorder(null);
        btnDataSupplier7.setBorderPainted(false);
        btnDataSupplier7.setContentAreaFilled(false);
        btnDataSupplier7.setFocusPainted(false);
        btnDataSupplier7.setFocusable(false);
        btnDataSupplier7.addActionListener(this::btnDataSupplier7ActionPerformed);
        getContentPane().add(btnDataSupplier7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, 20));

        btnBarangMasuk7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangMasuk7.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangMasuk7.setText("Barang Masuk");
        btnBarangMasuk7.setBorder(null);
        btnBarangMasuk7.setBorderPainted(false);
        btnBarangMasuk7.setContentAreaFilled(false);
        btnBarangMasuk7.setFocusPainted(false);
        btnBarangMasuk7.setFocusable(false);
        btnBarangMasuk7.addActionListener(this::btnBarangMasuk7ActionPerformed);
        getContentPane().add(btnBarangMasuk7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, 30));

        btnBarangKeluar7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBarangKeluar7.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangKeluar7.setText("Barang Keluar");
        btnBarangKeluar7.setBorder(null);
        btnBarangKeluar7.setBorderPainted(false);
        btnBarangKeluar7.setContentAreaFilled(false);
        btnBarangKeluar7.setFocusPainted(false);
        btnBarangKeluar7.setFocusable(false);
        btnBarangKeluar7.addActionListener(this::btnBarangKeluar7ActionPerformed);
        getContentPane().add(btnBarangKeluar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 110, 30));

        btnlLaporan7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnlLaporan7.setForeground(new java.awt.Color(201, 160, 160));
        btnlLaporan7.setText("Laporan");
        btnlLaporan7.setBorder(null);
        btnlLaporan7.setBorderPainted(false);
        btnlLaporan7.setContentAreaFilled(false);
        btnlLaporan7.setFocusPainted(false);
        btnlLaporan7.setFocusable(false);
        btnlLaporan7.addActionListener(this::btnlLaporan7ActionPerformed);
        getContentPane().add(btnlLaporan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, 30));

        btnSetting7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSetting7.setForeground(new java.awt.Color(201, 160, 160));
        btnSetting7.setText("Setting");
        btnSetting7.setBorder(null);
        btnSetting7.setBorderPainted(false);
        btnSetting7.setContentAreaFilled(false);
        btnSetting7.setFocusPainted(false);
        btnSetting7.setFocusable(false);
        btnSetting7.addActionListener(this::btnSetting7ActionPerformed);
        getContentPane().add(btnSetting7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 110, 30));

        btnAbout7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAbout7.setForeground(new java.awt.Color(201, 160, 160));
        btnAbout7.setText("About");
        btnAbout7.setBorder(null);
        btnAbout7.setBorderPainted(false);
        btnAbout7.setContentAreaFilled(false);
        btnAbout7.setFocusPainted(false);
        btnAbout7.setFocusable(false);
        btnAbout7.addActionListener(this::btnAbout7ActionPerformed);
        getContentPane().add(btnAbout7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 110, 40));

        btnLogout7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout7.setForeground(new java.awt.Color(201, 160, 160));
        btnLogout7.setText("Logout");
        btnLogout7.setBorder(null);
        btnLogout7.setBorderPainted(false);
        btnLogout7.setContentAreaFilled(false);
        btnLogout7.setFocusPainted(false);
        btnLogout7.setFocusable(false);
        btnLogout7.addActionListener(this::btnLogout7ActionPerformed);
        getContentPane().add(btnLogout7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 110, 40));

        lblIdUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIdUser.setForeground(new java.awt.Color(153, 153, 153));
        lblIdUser.setText("ID Profil");
        getContentPane().add(lblIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 460, 40));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(153, 153, 153));
        lblEmail.setText("Ubah Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 460, 40));

        lblNamaLengkap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNamaLengkap.setForeground(new java.awt.Color(153, 153, 153));
        lblNamaLengkap.setText("Nama Lengkap");
        getContentPane().add(lblNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 460, 40));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(153, 153, 153));
        lblUsername.setText("Username");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 460, 40));

        lblWhatshApp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblWhatshApp.setForeground(new java.awt.Color(153, 153, 153));
        lblWhatshApp.setText("Ubah WhatshApp");
        getContentPane().add(lblWhatshApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 460, 40));

        btnRefPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/click 20px.png"))); // NOI18N
        btnRefPassword.setBorder(null);
        btnRefPassword.setBorderPainted(false);
        btnRefPassword.setContentAreaFilled(false);
        btnRefPassword.setFocusPainted(false);
        btnRefPassword.setFocusable(false);
        btnRefPassword.setRequestFocusEnabled(false);
        btnRefPassword.addActionListener(this::btnRefPasswordActionPerformed);
        getContentPane().add(btnRefPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 30, 20));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(153, 153, 153));
        lblPassword.setText("Ubah Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 460, 40));

        btnRefWhatshApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/click 20px.png"))); // NOI18N
        btnRefWhatshApp.setBorder(null);
        btnRefWhatshApp.setBorderPainted(false);
        btnRefWhatshApp.setContentAreaFilled(false);
        btnRefWhatshApp.setFocusPainted(false);
        btnRefWhatshApp.setFocusable(false);
        btnRefWhatshApp.setRequestFocusEnabled(false);
        btnRefWhatshApp.addActionListener(this::btnRefWhatshAppActionPerformed);
        getContentPane().add(btnRefWhatshApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 30, 20));

        btnRefEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/icon/click 20px.png"))); // NOI18N
        btnRefEmail.setBorder(null);
        btnRefEmail.setBorderPainted(false);
        btnRefEmail.setContentAreaFilled(false);
        btnRefEmail.setFocusPainted(false);
        btnRefEmail.setFocusable(false);
        btnRefEmail.setRequestFocusEnabled(false);
        btnRefEmail.addActionListener(this::btnRefEmailActionPerformed);
        getContentPane().add(btnRefEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 30, 20));

        lblBackgroundSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/background/setting.png"))); // NOI18N
        getContentPane().add(lblBackgroundSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefPasswordActionPerformed

    private void btnRefWhatshAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefWhatshAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefWhatshAppActionPerformed

    private void btnRefEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefEmailActionPerformed

    private void btnDashboard7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard7ActionPerformed
        // TODO add your handling code here:
        dashboard();
    }//GEN-LAST:event_btnDashboard7ActionPerformed

    private void btnDataProduk7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataProduk7ActionPerformed
        // TODO add your handling code here:
        dataProduk();
    }//GEN-LAST:event_btnDataProduk7ActionPerformed

    private void btnDataSupplier7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSupplier7ActionPerformed
        // TODO add your handling code here:
        dataSupplier();
    }//GEN-LAST:event_btnDataSupplier7ActionPerformed

    private void btnBarangMasuk7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangMasuk7ActionPerformed
        // TODO add your handling code here:
        barangMasuk();
    }//GEN-LAST:event_btnBarangMasuk7ActionPerformed

    private void btnBarangKeluar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangKeluar7ActionPerformed
        // TODO add your handling code here:
        barangKeluar();
    }//GEN-LAST:event_btnBarangKeluar7ActionPerformed

    private void btnlLaporan7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlLaporan7ActionPerformed
        // TODO add your handling code here:
        laporan();
    }//GEN-LAST:event_btnlLaporan7ActionPerformed

    private void btnSetting7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetting7ActionPerformed
        // TODO add your handling code here:
        halamanAktif("Setting");
    }//GEN-LAST:event_btnSetting7ActionPerformed

    private void btnAbout7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbout7ActionPerformed
        // TODO add your handling code here:
        about();
    }//GEN-LAST:event_btnAbout7ActionPerformed

    private void btnLogout7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout7ActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_btnLogout7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SettingFrom().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout7;
    private javax.swing.JButton btnBarangKeluar7;
    private javax.swing.JButton btnBarangMasuk7;
    private javax.swing.JButton btnDashboard7;
    private javax.swing.JButton btnDataProduk7;
    private javax.swing.JButton btnDataSupplier7;
    private javax.swing.JButton btnLogout7;
    private javax.swing.JButton btnRefEmail;
    private javax.swing.JButton btnRefPassword;
    private javax.swing.JButton btnRefWhatshApp;
    private javax.swing.JButton btnSetting7;
    private javax.swing.JButton btnlLaporan7;
    private javax.swing.JLabel lblBackgroundSetting;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIdUser;
    private javax.swing.JLabel lblNamaLengkap;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWhatshApp;
    // End of variables declaration//GEN-END:variables
}
