/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_hijabella_collection;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class UbahWhatshAppFrom extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UbahWhatshAppFrom.class.getName());

    /**
     * Creates new form UbahWhatshAppFrom
     */
    public UbahWhatshAppFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInputWhatshAppLama = new javax.swing.JTextField();
        txtInputWhatshAppBaru = new javax.swing.JTextField();
        txtConfirmNoWhatshAppBaru = new javax.swing.JTextField();
        btnSimpanWhatshApp = new javax.swing.JButton();
        lblWhatshApp = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        lblBackgroundUbahWhatshApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ubah WhatshApp");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInputWhatshAppLama.setBackground(new java.awt.Color(245, 239, 231));
        txtInputWhatshAppLama.setForeground(new java.awt.Color(153, 153, 153));
        txtInputWhatshAppLama.setText("No WhatshApp Sebelumnya");
        txtInputWhatshAppLama.setBorder(null);
        txtInputWhatshAppLama.addActionListener(this::txtInputWhatshAppLamaActionPerformed);
        getContentPane().add(txtInputWhatshAppLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 280, 40));

        txtInputWhatshAppBaru.setForeground(new java.awt.Color(153, 153, 153));
        txtInputWhatshAppBaru.setText("No WhatshApp Baru");
        txtInputWhatshAppBaru.setBorder(null);
        getContentPane().add(txtInputWhatshAppBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 280, 30));

        txtConfirmNoWhatshAppBaru.setForeground(new java.awt.Color(153, 153, 153));
        txtConfirmNoWhatshAppBaru.setText("Konfirmasi No WhatshApp Baru");
        txtConfirmNoWhatshAppBaru.setBorder(null);
        getContentPane().add(txtConfirmNoWhatshAppBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 280, 30));

        btnSimpanWhatshApp.setBackground(new java.awt.Color(96, 60, 17));
        btnSimpanWhatshApp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpanWhatshApp.setForeground(new java.awt.Color(201, 160, 160));
        btnSimpanWhatshApp.setText("Simpan");
        btnSimpanWhatshApp.setBorder(null);
        btnSimpanWhatshApp.setBorderPainted(false);
        btnSimpanWhatshApp.setContentAreaFilled(false);
        btnSimpanWhatshApp.setFocusPainted(false);
        btnSimpanWhatshApp.addActionListener(this::btnSimpanWhatshAppActionPerformed);
        getContentPane().add(btnSimpanWhatshApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 340, 30));

        lblWhatshApp.setText("Nggak Jadi Ubah WhatshApp?");
        getContentPane().add(lblWhatshApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 180, 20));

        btnKembali.setForeground(new java.awt.Color(51, 153, 255));
        btnKembali.setText("Kembali!");
        btnKembali.setBorder(null);
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.addActionListener(this::btnKembaliActionPerformed);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 100, -1));

        lblBackgroundUbahWhatshApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/background/ubahwhatshapp.png"))); // NOI18N
        getContentPane().add(lblBackgroundUbahWhatshApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputWhatshAppLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputWhatshAppLamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputWhatshAppLamaActionPerformed

    private void btnSimpanWhatshAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanWhatshAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanWhatshAppActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        LoadingForm loading
        = new LoadingForm("Membuka Halaman Login", "Login");

        loading.setVisible(true);
        loading.mulaiLoading();

        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UbahWhatshAppFrom().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpanWhatshApp;
    private javax.swing.JLabel lblBackgroundUbahWhatshApp;
    private javax.swing.JLabel lblWhatshApp;
    private javax.swing.JTextField txtConfirmNoWhatshAppBaru;
    private javax.swing.JTextField txtInputWhatshAppBaru;
    private javax.swing.JTextField txtInputWhatshAppLama;
    // End of variables declaration//GEN-END:variables
}
