/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_hijabella_collection;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class UbahEmailForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UbahEmailForm.class.getName());

    /**
     * Creates new form UbahEmailForm
     */
    public UbahEmailForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInputEmailLama = new javax.swing.JTextField();
        txtInputEmailBaru = new javax.swing.JTextField();
        txtConfirmEmailBaru = new javax.swing.JTextField();
        btnSimpanEmail = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        btnKembali2 = new javax.swing.JButton();
        lblBackgroundUbahEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ubah Email");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInputEmailLama.setBackground(new java.awt.Color(245, 239, 231));
        txtInputEmailLama.setForeground(new java.awt.Color(153, 153, 153));
        txtInputEmailLama.setText("Email Sebelumnya");
        txtInputEmailLama.setBorder(null);
        txtInputEmailLama.addActionListener(this::txtInputEmailLamaActionPerformed);
        getContentPane().add(txtInputEmailLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 280, 40));

        txtInputEmailBaru.setForeground(new java.awt.Color(153, 153, 153));
        txtInputEmailBaru.setText("Email Baru");
        txtInputEmailBaru.setBorder(null);
        getContentPane().add(txtInputEmailBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 280, 30));

        txtConfirmEmailBaru.setForeground(new java.awt.Color(153, 153, 153));
        txtConfirmEmailBaru.setText("Konfirmasi Email Baru");
        txtConfirmEmailBaru.setBorder(null);
        getContentPane().add(txtConfirmEmailBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 280, 30));

        btnSimpanEmail.setBackground(new java.awt.Color(96, 60, 17));
        btnSimpanEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpanEmail.setForeground(new java.awt.Color(201, 160, 160));
        btnSimpanEmail.setText("Simpan");
        btnSimpanEmail.setBorder(null);
        btnSimpanEmail.setBorderPainted(false);
        btnSimpanEmail.setContentAreaFilled(false);
        btnSimpanEmail.setFocusPainted(false);
        btnSimpanEmail.addActionListener(this::btnSimpanEmailActionPerformed);
        getContentPane().add(btnSimpanEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 340, 30));

        lblEmail.setText("Nggak Jadi Ubah Email?");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 180, 20));

        btnKembali2.setForeground(new java.awt.Color(51, 153, 255));
        btnKembali2.setText("Kembali!");
        btnKembali2.setBorder(null);
        btnKembali2.setBorderPainted(false);
        btnKembali2.setContentAreaFilled(false);
        btnKembali2.addActionListener(this::btnKembali2ActionPerformed);
        getContentPane().add(btnKembali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 100, -1));

        lblBackgroundUbahEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_hijabella_collection/background/ubahemail.png"))); // NOI18N
        getContentPane().add(lblBackgroundUbahEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanEmailActionPerformed

    private void txtInputEmailLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputEmailLamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputEmailLamaActionPerformed

    private void btnKembali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali2ActionPerformed
        // TODO add your handling code here:
        LoadingForm loading
        = new LoadingForm("Membuka Halaman Setting", "Setting");

        loading.setVisible(true);
        loading.mulaiLoading();

        dispose();
    }//GEN-LAST:event_btnKembali2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UbahEmailForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali2;
    private javax.swing.JButton btnSimpanEmail;
    private javax.swing.JLabel lblBackgroundUbahEmail;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JTextField txtConfirmEmailBaru;
    private javax.swing.JTextField txtInputEmailBaru;
    private javax.swing.JTextField txtInputEmailLama;
    // End of variables declaration//GEN-END:variables
}
